export const SIDENAVSTATUS = "SIDENAVSTATUS";
export const PACKEGEBUTTONON = "PACKEGEBUTTONON";
export const CUSTOMERBUTTONON = "CUSTOMERBUTTONON";
export const FEEDBACKBUTTONON = "FEEDBACKBUTTONON";
export const ADDDETAILBUTTONON = "ADDDETAILBUTTONON";
