module.exports = {
  SignUp: "http://localhost:4000/api/users/SignUp",
  SignIn: "http://localhost:4000/api/users/SignIn",
  GetAllPackeges: "http://localhost:4000/api/users/GetAllPackeges",
  GetAllCustomers: "http://localhost:4000/api/users/GetAllCustomers",
  GetUserDetailById: "http://localhost:4000/api/users/GetUserDetailById",
  addUserDetail: "http://localhost:4000/api/users/addUserDetail",
  SubmitFeedback: "http://localhost:4000/api/users/SubmitFeedback",
  GetAllFeedBack: "http://localhost:4000/api/users/GetAllFeedBack",
  AddUserFeedBack: "http://localhost:4000/api/users/AddUserFeedBack",
  GetUserBuyPackages: "http://localhost:4000/api/users/GetUserBuyPackages",
  GetAllUserByPackages: "http://localhost:4000/api/users/GetAllUserByPackages",
  AddBuyUserPackages: "http://localhost:4000/api/users/AddBuyUserPackages",
  AddNewPackagesDetail: "http://localhost:4000/api/users/AddNewPackagesDetail",
  AdminRestriction: "http://localhost:4000/api/users/AdminRestriction",
};
